/**
 * config.mjs — load, validate and normalize `sfdx-pipeline.config.yml`.
 *
 * The config file is the single source of truth: GitHub Actions, the local CLI
 * and the Claude Code skills all read it. Validation is therefore strict and
 * loud — a typo in a test level or a threshold must fail at `validate` time,
 * not halfway through a deployment.
 *
 * Every error carries the YAML path it came from (`pipeline_settings.unit_test.
 * test_level`) so the message points at the line to edit.
 */

import fs from "node:fs";
import path from "node:path";
// js-yaml v5 is ESM with named exports only — there is no default export.
import { load as parseYaml } from "js-yaml";

export const CONFIG_FILENAME = "sfdx-pipeline.config.yml";
export const CONFIG_FILENAMES = [CONFIG_FILENAME, "sfdx-pipeline.config.yaml"];

export const SUPPORTED_VERSIONS = ["1.0"];
export const ENV_TYPES = ["sandbox", "production", "scratch", "developer"];
export const TEST_LEVELS = [
  "NoTestRun",
  "RunSpecifiedTests",
  "RunLocalTests",
  "RunAllTestsInOrg",
];
export const ANALYZER_ENGINES = ["code-analyzer", "scanner"];
export const INTEGRATION_TOOLS = ["newman", "custom"];
export const E2E_TOOLS = ["playwright", "custom"];

/** Stage ids, in the order the pipeline runs them. */
export const STAGE_ORDER = [
  "lint",
  "prettier",
  "code_analyzer",
  "validate_deploy",
  "unit_test",
  "deploy",
  "integration_test",
  "e2e_test",
  "documentation",
];

const DEFAULTS = {
  version: "1.0",
  project_name: "sfdx-project",
  environments: {},
  pipeline_settings: {
    lint: { enabled: true, fail_on_error: true, command: "npm run lint" },
    prettier: { enabled: true, fail_on_error: true, command: "npm run prettier" },
    code_analyzer: {
      enabled: true,
      engine: "code-analyzer",
      rule_selector: "Recommended",
      pmd_rule_set: "",
      severity_threshold: 3,
      target: "force-app",
      output_file: "code-analyzer-results.json",
    },
    // Validation runs everywhere; the real deployment is additionally gated to
    // non-pull-request events by the generated workflow.
    validate_deploy: { enabled: true },
    deploy: { enabled: true },
    unit_test: {
      enabled: true,
      test_level: "RunLocalTests",
      tests: [],
      coverage_threshold: 75,
    },
    integration_test: { enabled: true, tool: "newman", command: "" },
    e2e_test: { enabled: true, tool: "playwright", command: "npx playwright test" },
    // Documentation is generated by rtk-sf, which ships as the default AI
    // companion. It degrades to a warning when rtk-sf is not installed.
    documentation: {
      enabled: true,
      tool: "rtk-sf",
      doc_type: "all",
      output_dir: "docs",
    },
  },
  // rtk-sf is integrated by default. `required: false` keeps the kit usable in
  // projects that have not installed it: stages needing it warn and skip.
  ai_assist: {
    rtk_sf: {
      enabled: true,
      required: false,
      python: "python3",
      index_on_setup: true,
      register_mcp: true,
    },
  },
  backlog_integration: {
    project_key: "",
    branch_pattern: "([A-Z][A-Z0-9_]*-\\d+)",
    status_mapping: {
      in_progress: "処理中",
      review_ready: "処理済み",
      closed: "完了",
    },
    // nulab/backlog-mcp-server exposes no status-listing tool, so a status name
    // cannot be resolved to an id at runtime. Backlog's built-in statuses have
    // fixed ids in every project; a project with custom statuses must map them
    // here explicitly, otherwise the skills post their comment and report that
    // the status was left alone rather than guessing an id.
    status_ids: {},
    mcp: {
      server_name: "backlog",
      runtime: "docker",
      toolsets: "space,project,issue",
      tool_prefix: "",
    },
    deliverables: {
      post_on_review: true,
      include_package_xml: true,
      include_non_metadata: true,
      // A reviewer should reach the code from the ticket in one click.
      include_pr_link: true,
    },
  },
};

/** Backlog's built-in status ids, identical across projects. */
export const STANDARD_BACKLOG_STATUS_IDS = {
  未対応: 1,
  "処理中": 2,
  "処理済み": 3,
  完了: 4,
  Open: 1,
  "In Progress": 2,
  Resolved: 3,
  Closed: 4,
};

export const BACKLOG_RUNTIMES = ["docker", "npx"];

class ConfigError extends Error {}

/** Deep-merge plain objects; arrays and scalars from `override` win outright. */
function merge(base, override) {
  if (!isPlainObject(base) || !isPlainObject(override)) {
    return override === undefined ? base : override;
  }
  const out = { ...base };
  for (const [key, value] of Object.entries(override)) {
    out[key] = key in base ? merge(base[key], value) : value;
  }
  return out;
}

function isPlainObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Locate the config file by walking up from `cwd`. */
export function findConfigFile(cwd = process.cwd()) {
  let dir = path.resolve(cwd);
  for (;;) {
    for (const name of CONFIG_FILENAMES) {
      const candidate = path.join(dir, name);
      if (fs.existsSync(candidate)) return candidate;
    }
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

/**
 * Load and validate the config.
 *
 * @returns {{config: object, file: string|null, errors: string[], warnings: string[]}}
 */
export function loadConfig({ cwd = process.cwd(), file } = {}) {
  const configFile = file ? path.resolve(cwd, file) : findConfigFile(cwd);
  if (!configFile) {
    return {
      config: null,
      file: null,
      errors: [
        `${CONFIG_FILENAME} not found (searched ${path.resolve(cwd)} and its parents). ` +
          `Run \`sfdx-devops-kit init\` to create one.`,
      ],
      warnings: [],
    };
  }

  let raw;
  try {
    raw = parseYaml(fs.readFileSync(configFile, "utf8"));
  } catch (error) {
    return {
      config: null,
      file: configFile,
      errors: [`${path.basename(configFile)} is not valid YAML: ${error.message}`],
      warnings: [],
    };
  }

  if (!isPlainObject(raw)) {
    return {
      config: null,
      file: configFile,
      errors: [`${path.basename(configFile)} must contain a YAML mapping at the top level.`],
      warnings: [],
    };
  }

  const { config, errors, warnings } = validateConfig(raw);
  return { config, file: configFile, errors, warnings };
}

/**
 * Apply defaults and validate. Pure — safe to call on parsed YAML in tests.
 *
 * @returns {{config: object, errors: string[], warnings: string[]}}
 */
export function validateConfig(raw) {
  const errors = [];
  const warnings = [];
  const config = merge(DEFAULTS, raw ?? {});

  if (!SUPPORTED_VERSIONS.includes(String(config.version))) {
    errors.push(
      `version: "${config.version}" is not supported (expected one of ${SUPPORTED_VERSIONS.join(", ")}).`,
    );
  }
  if (!config.project_name || typeof config.project_name !== "string") {
    errors.push("project_name must be a non-empty string.");
  }

  validateEnvironments(config, errors, warnings);
  validatePipeline(config, errors, warnings);
  validateAiAssist(config, errors, warnings);
  validateBacklog(config, errors, warnings);

  return { config, errors, warnings };
}

function validateEnvironments(config, errors, warnings) {
  const envs = config.environments;
  if (!isPlainObject(envs) || Object.keys(envs).length === 0) {
    errors.push("environments must declare at least one environment (e.g. `st`).");
    return;
  }

  let testTargets = 0;
  for (const [key, env] of Object.entries(envs)) {
    const at = `environments.${key}`;
    if (!isPlainObject(env)) {
      errors.push(`${at} must be a mapping.`);
      continue;
    }
    if (!env.alias) errors.push(`${at}.alias is required (org alias or username).`);
    if (!env.type) {
      errors.push(`${at}.type is required (one of ${ENV_TYPES.join(", ")}).`);
    } else if (!ENV_TYPES.includes(env.type)) {
      errors.push(`${at}.type: "${env.type}" is invalid (expected ${ENV_TYPES.join(", ")}).`);
    }

    // The Salesforce CLI rejects --manifest, --source-dir and --metadata in
    // combination, so the config may declare exactly one deployment selector.
    const selectors = ["deploy_manifest", "source_dir", "metadata"].filter((name) => {
      const value = env[name];
      return Array.isArray(value) ? value.length > 0 : Boolean(value);
    });
    if (selectors.length > 1) {
      errors.push(
        `${at} declares ${selectors.join(" and ")}, but the Salesforce CLI rejects those flags ` +
          `together. Keep exactly one deployment selector per environment.`,
      );
    }

    if (env.is_test_target) testTargets += 1;
    if (env.type === "production" && env.is_test_target) {
      errors.push(`${at}.is_test_target must not be set on a production environment.`);
    }
  }

  if (testTargets === 0) {
    warnings.push(
      "No environment sets `is_test_target: true`; CI validation and E2E stages have no default " +
        "target. Mark your integration sandbox (commonly `st`).",
    );
  } else if (testTargets > 1) {
    errors.push("Only one environment may set `is_test_target: true`.");
  }
}

function validatePipeline(config, errors, warnings) {
  const settings = config.pipeline_settings;
  if (!isPlainObject(settings)) {
    errors.push("pipeline_settings must be a mapping.");
    return;
  }

  for (const [key, stage] of Object.entries(settings)) {
    if (!STAGE_ORDER.includes(key)) {
      warnings.push(`pipeline_settings.${key} is not a known stage and will be ignored.`);
      continue;
    }
    if (!isPlainObject(stage)) {
      errors.push(`pipeline_settings.${key} must be a mapping.`);
      continue;
    }
    if (typeof stage.enabled !== "boolean") {
      errors.push(`pipeline_settings.${key}.enabled must be true or false.`);
    }
  }

  const analyzer = settings.code_analyzer ?? {};
  if (!ANALYZER_ENGINES.includes(analyzer.engine)) {
    errors.push(
      `pipeline_settings.code_analyzer.engine: "${analyzer.engine}" is invalid ` +
        `(expected ${ANALYZER_ENGINES.join(" or ")}).`,
    );
  }
  if (!Number.isInteger(analyzer.severity_threshold) ||
      analyzer.severity_threshold < 1 || analyzer.severity_threshold > 5) {
    errors.push(
      "pipeline_settings.code_analyzer.severity_threshold must be an integer from 1 (Critical) to 5 (Info).",
    );
  }

  const unit = settings.unit_test ?? {};
  if (!TEST_LEVELS.includes(unit.test_level)) {
    errors.push(
      `pipeline_settings.unit_test.test_level: "${unit.test_level}" is invalid ` +
        `(expected ${TEST_LEVELS.join(", ")}).`,
    );
  }
  if (unit.test_level === "RunSpecifiedTests" && (unit.tests ?? []).length === 0) {
    errors.push(
      "pipeline_settings.unit_test.test_level is RunSpecifiedTests, so `tests` must list at least " +
        "one Apex test class.",
    );
  }
  if (unit.test_level === "NoTestRun" && unit.enabled) {
    warnings.push(
      "pipeline_settings.unit_test.test_level is NoTestRun while the stage is enabled: no Apex test " +
        "will run and coverage cannot be verified.",
    );
  }
  if (typeof unit.coverage_threshold !== "number" ||
      unit.coverage_threshold < 0 || unit.coverage_threshold > 100) {
    errors.push("pipeline_settings.unit_test.coverage_threshold must be a number from 0 to 100.");
  }

  const integration = settings.integration_test ?? {};
  if (!INTEGRATION_TOOLS.includes(integration.tool)) {
    errors.push(
      `pipeline_settings.integration_test.tool: "${integration.tool}" is invalid ` +
        `(expected ${INTEGRATION_TOOLS.join(" or ")}).`,
    );
  }
  if (integration.enabled && integration.tool === "custom" && !integration.command) {
    errors.push(
      "pipeline_settings.integration_test.tool is `custom`, so `command` must say what to run.",
    );
  }

  const e2e = settings.e2e_test ?? {};
  if (!E2E_TOOLS.includes(e2e.tool)) {
    errors.push(
      `pipeline_settings.e2e_test.tool: "${e2e.tool}" is invalid (expected ${E2E_TOOLS.join(" or ")}).`,
    );
  }
  if (e2e.enabled && e2e.tool === "custom" && !e2e.command) {
    errors.push("pipeline_settings.e2e_test.tool is `custom`, so `command` must say what to run.");
  }

  const docs = settings.documentation ?? {};
  if (docs.enabled && docs.tool !== "rtk-sf") {
    warnings.push(
      `pipeline_settings.documentation.tool: "${docs.tool}" is not a tool this kit knows how to ` +
        "drive; only `rtk-sf` is wired up.",
    );
  }
  if (docs.enabled && config.ai_assist?.rtk_sf?.enabled === false) {
    warnings.push(
      "pipeline_settings.documentation is enabled but ai_assist.rtk_sf.enabled is false; the " +
        "documentation stage will be skipped.",
    );
  }
}

function validateAiAssist(config, errors) {
  const rtk = config.ai_assist?.rtk_sf;
  if (!isPlainObject(rtk)) {
    errors.push("ai_assist.rtk_sf must be a mapping.");
    return;
  }
  for (const flag of ["enabled", "required", "index_on_setup", "register_mcp"]) {
    if (typeof rtk[flag] !== "boolean") {
      errors.push(`ai_assist.rtk_sf.${flag} must be true or false.`);
    }
  }
  if (!rtk.python) errors.push("ai_assist.rtk_sf.python must name a Python interpreter.");
}

function validateBacklog(config, errors, warnings) {
  const backlog = config.backlog_integration;
  if (!isPlainObject(backlog)) {
    errors.push("backlog_integration must be a mapping.");
    return;
  }
  if (!backlog.project_key) {
    warnings.push(
      "backlog_integration.project_key is empty: the review skill cannot resolve ticket keys from " +
        "branch names until it is set.",
    );
  }
  try {
    new RegExp(backlog.branch_pattern);
  } catch (error) {
    errors.push(`backlog_integration.branch_pattern is not a valid regular expression: ${error.message}`);
  }
  for (const key of ["in_progress", "review_ready", "closed"]) {
    if (!backlog.status_mapping?.[key]) {
      errors.push(`backlog_integration.status_mapping.${key} is required.`);
    }
  }

  const mcp = backlog.mcp ?? {};
  if (!mcp.server_name) {
    errors.push("backlog_integration.mcp.server_name is required (the name the MCP server is registered under).");
  }
  if (!BACKLOG_RUNTIMES.includes(mcp.runtime)) {
    errors.push(
      `backlog_integration.mcp.runtime: "${mcp.runtime}" is invalid (expected ${BACKLOG_RUNTIMES.join(" or ")}).`,
    );
  }

  const ids = backlog.status_ids ?? {};
  if (!isPlainObject(ids)) {
    errors.push("backlog_integration.status_ids must be a mapping of status name to numeric id.");
  } else {
    for (const [name, id] of Object.entries(ids)) {
      if (!Number.isInteger(id) || id <= 0) {
        errors.push(`backlog_integration.status_ids["${name}"] must be a positive integer id.`);
      }
    }
    // Warn only for names that are neither configured nor standard: the skill
    // will post its comment but leave the status untouched.
    for (const phase of ["in_progress", "review_ready", "closed"]) {
      const name = backlog.status_mapping?.[phase];
      if (!name) continue;
      if (!(name in ids) && !(name in STANDARD_BACKLOG_STATUS_IDS)) {
        warnings.push(
          `backlog_integration.status_mapping.${phase} is "${name}", which is not a built-in Backlog ` +
            `status. Add backlog_integration.status_ids["${name}"] with its numeric id, or the ticket ` +
            `status will be left unchanged.`,
        );
      }
    }
  }
}

/**
 * Resolve a pipeline phase to a Backlog status name and id.
 *
 * @returns {{name: string, id: number|null, source: "config"|"standard"|"unresolved"}}
 */
export function resolveStatus(config, phase) {
  const backlog = config.backlog_integration ?? {};
  const name = backlog.status_mapping?.[phase];
  if (!name) {
    throw new ConfigError(
      `No Backlog status mapped for phase "${phase}" (backlog_integration.status_mapping).`,
    );
  }
  const configured = backlog.status_ids?.[name];
  if (Number.isInteger(configured)) return { name, id: configured, source: "config" };
  const standard = STANDARD_BACKLOG_STATUS_IDS[name];
  if (Number.isInteger(standard)) return { name, id: standard, source: "standard" };
  return { name, id: null, source: "unresolved" };
}

/** Tool names to call on the Backlog MCP server, honouring --prefix. */
export function backlogTools(config) {
  const prefix = config.backlog_integration?.mcp?.tool_prefix ?? "";
  const name = (tool) => `${prefix}${tool}`;
  return {
    server: config.backlog_integration?.mcp?.server_name ?? "backlog",
    getIssue: name("get_issue"),
    getIssues: name("get_issues"),
    addIssue: name("add_issue"),
    updateIssue: name("update_issue"),
    addComment: name("add_issue_comment"),
    getComments: name("get_issue_comments"),
    getProject: name("get_project"),
    getIssueTypes: name("get_issue_types"),
    getPriorities: name("get_priorities"),
    getMyself: name("get_myself"),
  };
}

/**
 * Resolve one environment by key, or the `is_test_target` one when no key is given.
 *
 * @throws {ConfigError} when the key is unknown or no default exists.
 */
export function resolveEnvironment(config, key) {
  const envs = config.environments ?? {};
  if (key) {
    if (!envs[key]) {
      const known = Object.keys(envs).join(", ") || "none declared";
      throw new ConfigError(`Unknown environment "${key}". Declared environments: ${known}.`);
    }
    return { key, ...envs[key] };
  }
  const found = Object.entries(envs).find(([, env]) => env.is_test_target);
  if (!found) {
    throw new ConfigError(
      "No environment given and none sets `is_test_target: true`. Pass --env <key>.",
    );
  }
  return { key: found[0], ...found[1] };
}

/** GitHub Secret name holding an environment's SFDX auth URL. */
export function authSecretName(env) {
  if (env.auth_secret) return env.auth_secret;
  return `SF_${String(env.key).toUpperCase().replace(/[^A-Z0-9]/g, "_")}_AUTH_URL`;
}

/** The deployment selector flag for an environment, or null to deploy the default package. */
export function deploySelector(env) {
  if (env.deploy_manifest) return { flag: "--manifest", value: env.deploy_manifest };
  if (env.source_dir) return { flag: "--source-dir", value: env.source_dir };
  if (env.metadata) return { flag: "--metadata", value: env.metadata };
  return null;
}

export { ConfigError, DEFAULTS };
